name: Publish package to npm
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install && npm install @rollup/rollup-linux-x64-gnu --save-optional

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm run build && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
